"""
example_sequences.py

Every sequence here is either (a) the exact example sequence given in the
WISER/Moderna challenge document itself, or (b) synthetic / randomly
generated by us. NONE of these are real Moderna sequences or any kind of
proprietary/clinical data -- per the challenge's data-privacy rules, that's
exactly the category you're required to stick to for this project.

Start with `toy_hairpin_9nt` (small enough to brute-force AND to reason
about by hand -- it's what classical_solvers.py, quantum_solver_qaoa.py,
and PROJECT_LOG.md all use as the running example) and work your way down
this dict as your pipeline gets more solid.
"""

EXAMPLE_SEQUENCES = {
    # Hand-built minimal hairpin: a 3-bp GC stem around a 3-nt loop.
    # Small enough (9 candidate-pair qubits) to brute-force exactly --
    # this is the sanity-check example used throughout this project.
    "toy_hairpin_9nt": "GGGAAACCC",

    # A second small hand-built example, 2 nt longer with an extra
    # unpaired base worked into the stem region. Still small enough to
    # brute-force (10 qubits) -- verified with benchmark_runner.py, the
    # optimal simplified-objective structure it actually finds is a plain
    # 3-bp stem "(((.....)))", same as toy_hairpin_9nt; use it as a second
    # independent check that Nussinov and the QUBO agree, not as an
    # example of a bulge motif (edit the sequence if you want one that
    # actually forces a bulge into the optimal structure).
    "toy_bulge_11nt": "GGGACAAGCCC",

    # --- QAOA-feasible batch (added after the first real experiment round) ---
    # All of these were checked with qubo_builder.build_qubo and confirmed
    # <=24 qubits -- comfortably under the ~27-qubit ceiling for exact
    # statevector simulation on qBraid's Small tier (4 GB RAM; see
    # quantum_solver_qaoa.max_safe_qubits). Unlike challenge_example_44nt
    # and random_30nt_seed11 below, QAOA can actually run on every one of
    # these without hitting the memory wall -- use --max-qubits-qaoa 24
    # with run_experiments.py to include all of them.
    "hairpin_A_12nt": "GGGCAAAAGCCC",          # 10 qubits, designed hairpin
    "hairpin_B_14nt": "CCGGGAAAACCCGG",        # 15 qubits, designed hairpin
    "stem_bulge_15nt": "GGGGCAUAAAGCCCC",      # 23 qubits, designed, has an internal bulge
    "random_12nt_seedA": "UUAGUUGUGCCG",       # 15 qubits
    "random_12nt_seedB": "CAGAUUUUCAUA",       # 16 qubits
    "random_15nt_seedA": "CCGUAAUGCCUUUCC",    # 21 qubits
    "random_15nt_seedB": "CGAUUCAAAUGACGG",    # 23 qubits
    "random_18nt_seedA": "CCUACUACUCUCACCCCU", # 10 qubits
    "random_18nt_seedB": "ACCCCUUCCCUCCCCAUC", # 7 qubits (mostly unpaired -- a good contrast case)
    "random_20nt_seedA": "ACCCCUUCCCUCCCCAUCAA",# 13 qubits
    "random_20nt_seedB": "AUAUCACACCCAACCUUCAA",# 23 qubits

    # Deliberately JUST over budget (28 qubits on a hand-designed two-stem
    # sequence) -- keep this one specifically to show in your scaling
    # section that qubit count depends on sequence composition, not just
    # length: this is 16 nt (shorter than several sequences above) but
    # needs more qubits than any of them, because two well-separated stems
    # still generate many candidate CROSS pairs between the two regions
    # that never end up in the optimal structure but still count as QUBO
    # variables. Good discussion material, not a mistake to fix.
    "two_stem_16nt_over_budget": "GGGAACCCGGGAACCC",

    # The exact example sequence from the WISER/Moderna challenge document.
    # Too large to brute-force the QUBO directly (see scaling_analysis.py --
    # this needs the base-pair-probability filtering trick from
    # classical_reference.py, or a smarter encoding, before QAOA/VQE is
    # practical on it).
    "challenge_example_44nt": "GGAGCAAAACUUGUCGAUUGAGAACAAAAUACAGAAUUUGCUUG",

    # Randomly generated (seeded, reproducible) via
    # scaling_analysis.random_rna_sequence(20, seed=7) -- use these to
    # test that your pipeline isn't overfit to the two hand-built examples
    # above.
    "random_20nt_seed7": "GCUAAAGACAAUUACAUAAC",

    # Randomly generated via random_rna_sequence(30, seed=11) -- a second,
    # longer random instance for the low end of your scaling sweep.
    "random_30nt_seed11": "UUUCCUCAUGCAAUUCAAAACCAUGUCCGU",
}


if __name__ == "__main__":
    for name, seq in EXAMPLE_SEQUENCES.items():
        print(f"{name:>22}  (n={len(seq):>3}):  {seq}")
