"""
example_sequences.py

Every sequence here is either (a) the exact example sequence given in the
WISER/Moderna challenge document itself, or (b) synthetic / randomly
generated by us. NONE of these are real Moderna sequences or any kind of
proprietary/clinical data -- per the challenge's data-privacy rules, that's
exactly the category you're required to stick to for this project.

Start with `toy_hairpin_9nt` (small enough to brute-force AND to reason
about by hand -- it's what classical_solvers.py, quantum_solver_qaoa.py,
and PROJECT_LOG.md all use as the running example) and work your way down
this dict as your pipeline gets more solid.
"""

EXAMPLE_SEQUENCES = {
    # Hand-built minimal hairpin: a 3-bp GC stem around a 3-nt loop.
    # Small enough (9 candidate-pair qubits) to brute-force exactly --
    # this is the sanity-check example used throughout this project.
    "toy_hairpin_9nt": "GGGAAACCC",

    # A second small hand-built example, 2 nt longer with an extra
    # unpaired base worked into the stem region. Still small enough to
    # brute-force (10 qubits) -- verified with benchmark_runner.py, the
    # optimal simplified-objective structure it actually finds is a plain
    # 3-bp stem "(((.....)))", same as toy_hairpin_9nt; use it as a second
    # independent check that Nussinov and the QUBO agree, not as an
    # example of a bulge motif (edit the sequence if you want one that
    # actually forces a bulge into the optimal structure).
    "toy_bulge_11nt": "GGGACAAGCCC",

    # The exact example sequence from the WISER/Moderna challenge document.
    # Too large to brute-force the QUBO directly (see scaling_analysis.py --
    # this needs the base-pair-probability filtering trick from
    # classical_reference.py, or a smarter encoding, before QAOA/VQE is
    # practical on it).
    "challenge_example_44nt": "GGAGCAAAACUUGUCGAUUGAGAACAAAAUACAGAAUUUGCUUG",

    # Randomly generated (seeded, reproducible) via
    # scaling_analysis.random_rna_sequence(20, seed=7) -- use these to
    # test that your pipeline isn't overfit to the two hand-built examples
    # above.
    "random_20nt_seed7": "GCUAAAGACAAUUACAUAAC",

    # Randomly generated via random_rna_sequence(30, seed=11) -- a second,
    # longer random instance for the low end of your scaling sweep.
    "random_30nt_seed11": "UUUCCUCAUGCAAUUCAAAACCAUGUCCGU",
}


if __name__ == "__main__":
    for name, seq in EXAMPLE_SEQUENCES.items():
        print(f"{name:>22}  (n={len(seq):>3}):  {seq}")
